spiderJson = {"nodes":[
{"weight":2,"rank":0.0, "id":1, "url":"https://www.tdcj.texas.gov/death_row/dr_executed_offenders.html"},
{"weight":3,"rank":19.0, "id":2, "url":"https://www.tdcj.texas.gov/death_row/dr_info/ochoaabel.html"},
{"weight":3,"rank":19.0, "id":3, "url":"https://www.tdcj.texas.gov/death_row/dr_info/ochoaabellast.html"},
{"weight":3,"rank":19.0, "id":4, "url":"https://www.tdcj.texas.gov/death_row/dr_info/gardnerjohn.html"},
{"weight":3,"rank":19.0, "id":5, "url":"https://www.tdcj.texas.gov/death_row/dr_info/gardnerjohnlast.html"},
{"weight":3,"rank":19.0, "id":6, "url":"https://www.tdcj.texas.gov/death_row/dr_info/runnelstravis.html"},
{"weight":3,"rank":19.0, "id":7, "url":"https://www.tdcj.texas.gov/death_row/dr_info/runnelstravislast.html"},
{"weight":3,"rank":19.0, "id":8, "url":"https://www.tdcj.texas.gov/death_row/dr_info/halljusten.html"},
{"weight":3,"rank":19.0, "id":9, "url":"https://www.tdcj.texas.gov/death_row/dr_info/halljustenlast.html"},
{"weight":3,"rank":19.0, "id":10, "url":"https://www.tdcj.texas.gov/death_row/dr_info/sparksrobert.html"},
{"weight":3,"rank":19.0, "id":11, "url":"https://www.tdcj.texas.gov/death_row/dr_info/sparksrobertlast.html"},
{"weight":3,"rank":19.0, "id":12, "url":"https://www.tdcj.texas.gov/death_row/dr_info/solizmarkanthony.html"},
{"weight":3,"rank":19.0, "id":13, "url":"https://www.tdcj.texas.gov/death_row/dr_info/solizmarkanthonylast.html"},
{"weight":3,"rank":19.0, "id":14, "url":"https://www.tdcj.texas.gov/death_row/dr_info/crutsingerbilly.html"},
{"weight":3,"rank":19.0, "id":15, "url":"https://www.tdcj.texas.gov/death_row/dr_info/crutsingerbillylast.html"},
{"weight":3,"rank":19.0, "id":16, "url":"https://www.tdcj.texas.gov/death_row/dr_info/swearingenlarry.html"},
{"weight":3,"rank":19.0, "id":17, "url":"https://www.tdcj.texas.gov/death_row/dr_info/swearingenlarrylast.html"},
{"weight":3,"rank":19.0, "id":18, "url":"https://www.tdcj.texas.gov/death_row/dr_info/kingjohn.html"},
{"weight":3,"rank":19.0, "id":19, "url":"https://www.tdcj.texas.gov/death_row/dr_info/kingjohnlast.html"},
{"weight":3,"rank":19.0, "id":20, "url":"https://www.tdcj.texas.gov/death_row/dr_info/coblebillielast.html"},
{"weight":3,"rank":19.0, "id":21, "url":"https://www.tdcj.texas.gov/death_row/dr_info/jenningsrobertlast.html"},
{"weight":3,"rank":19.0, "id":22, "url":"https://www.tdcj.texas.gov/death_row/dr_info/brazielalvin.html"},
{"weight":3,"rank":19.0, "id":23, "url":"https://www.tdcj.texas.gov/death_row/dr_info/brazielalvinlast.html"},
{"weight":3,"rank":19.0, "id":24, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garciajoseph.html"},
{"weight":3,"rank":19.0, "id":25, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garciajosephlast.html"},
{"weight":3,"rank":19.0, "id":26, "url":"https://www.tdcj.texas.gov/death_row/dr_info/ramosrobertlast.html"},
{"weight":3,"rank":19.0, "id":27, "url":"https://www.tdcj.texas.gov/death_row/dr_info/ackerdaniel.html"},
{"weight":3,"rank":19.0, "id":28, "url":"https://www.tdcj.texas.gov/death_row/dr_info/ackerdaniellast.html"},
{"weight":3,"rank":19.0, "id":29, "url":"https://www.tdcj.texas.gov/death_row/dr_info/clarktroy.html"},
{"weight":3,"rank":19.0, "id":30, "url":"https://www.tdcj.texas.gov/death_row/dr_info/clarktroylast.html"},
{"weight":3,"rank":19.0, "id":31, "url":"https://www.tdcj.texas.gov/death_row/dr_info/youngchristopher.html"},
{"weight":3,"rank":19.0, "id":32, "url":"https://www.tdcj.texas.gov/death_row/dr_info/youngchristopherlast.html"},
{"weight":3,"rank":19.0, "id":33, "url":"https://www.tdcj.texas.gov/death_row/dr_info/bibledanny.html"},
{"weight":3,"rank":19.0, "id":34, "url":"https://www.tdcj.texas.gov/death_row/dr_info/bibledannylast.html"},
{"weight":3,"rank":19.0, "id":35, "url":"https://www.tdcj.texas.gov/death_row/dr_info/castillojuan.html"},
{"weight":3,"rank":19.0, "id":36, "url":"https://www.tdcj.texas.gov/death_row/dr_info/castillojuanlast.html"},
{"weight":3,"rank":19.0, "id":37, "url":"https://www.tdcj.texas.gov/death_row/dr_info/davilaerick.html"},
{"weight":3,"rank":19.0, "id":38, "url":"https://www.tdcj.texas.gov/death_row/dr_info/davilaericklast.html"},
{"weight":3,"rank":19.0, "id":39, "url":"https://www.tdcj.texas.gov/death_row/dr_info/rodriguezrosendo.html"},
{"weight":3,"rank":19.0, "id":40, "url":"https://www.tdcj.texas.gov/death_row/dr_info/rodriguezrosendolast.html"},
{"weight":3,"rank":19.0, "id":41, "url":"https://www.tdcj.texas.gov/death_row/dr_info/battagliajohn.html"},
{"weight":3,"rank":19.0, "id":42, "url":"https://www.tdcj.texas.gov/death_row/dr_info/battagliajohnlast.html"},
{"weight":3,"rank":19.0, "id":43, "url":"https://www.tdcj.texas.gov/death_row/dr_info/rayfordwilliam.html"},
{"weight":3,"rank":19.0, "id":44, "url":"https://www.tdcj.texas.gov/death_row/dr_info/rayfordwilliamlast.html"},
{"weight":3,"rank":19.0, "id":45, "url":"https://www.tdcj.texas.gov/death_row/dr_info/shoreanthony.html"},
{"weight":3,"rank":19.0, "id":46, "url":"https://www.tdcj.texas.gov/death_row/dr_info/shoreanthonylast.html"},
{"weight":3,"rank":19.0, "id":47, "url":"https://www.tdcj.texas.gov/death_row/dr_info/cardenasruben.html"},
{"weight":3,"rank":19.0, "id":48, "url":"https://www.tdcj.texas.gov/death_row/dr_info/cardenasrubenlast.html"},
{"weight":3,"rank":19.0, "id":49, "url":"https://www.tdcj.texas.gov/death_row/dr_info/pruettrobert.html"},
{"weight":3,"rank":19.0, "id":50, "url":"https://www.tdcj.texas.gov/death_row/dr_info/pruettrobertlast.html"},
{"weight":3,"rank":19.0, "id":51, "url":"https://www.tdcj.texas.gov/death_row/dr_info/preyortaichin.html"},
{"weight":3,"rank":19.0, "id":52, "url":"https://www.tdcj.texas.gov/death_row/dr_info/preyortaichinlast.html"},
{"weight":3,"rank":19.0, "id":53, "url":"https://www.tdcj.texas.gov/death_row/dr_info/bigbyjameslast.html"},
{"weight":3,"rank":19.0, "id":54, "url":"https://www.tdcj.texas.gov/death_row/dr_info/ruizrolandolast.html"},
{"weight":3,"rank":19.0, "id":55, "url":"https://www.tdcj.texas.gov/death_row/dr_info/edwardsterry.html"},
{"weight":3,"rank":19.0, "id":56, "url":"https://www.tdcj.texas.gov/death_row/dr_info/edwardsterrylast.html"},
{"weight":3,"rank":19.0, "id":57, "url":"https://www.tdcj.texas.gov/death_row/dr_info/wilkinschristopher.html"},
{"weight":3,"rank":19.0, "id":58, "url":"https://www.tdcj.texas.gov/death_row/dr_info/wilkinschristopherlast.html"},
{"weight":3,"rank":19.0, "id":59, "url":"https://www.tdcj.texas.gov/death_row/dr_info/fullerbarney.html"},
{"weight":3,"rank":19.0, "id":60, "url":"https://www.tdcj.texas.gov/death_row/dr_info/fullerbarneylast.html"},
{"weight":3,"rank":19.0, "id":61, "url":"https://www.tdcj.texas.gov/death_row/dr_info/vasquezpablo.html"},
{"weight":3,"rank":19.0, "id":62, "url":"https://www.tdcj.texas.gov/death_row/dr_info/vasquezpablolast.html"},
{"weight":3,"rank":19.0, "id":63, "url":"https://www.tdcj.texas.gov/death_row/dr_info/wardadam.html"},
{"weight":3,"rank":19.0, "id":64, "url":"https://www.tdcj.texas.gov/death_row/dr_info/wardadamlast.html"},
{"weight":3,"rank":19.0, "id":65, "url":"https://www.tdcj.texas.gov/death_row/dr_info/wesbrookcoy.html"},
{"weight":3,"rank":19.0, "id":66, "url":"https://www.tdcj.texas.gov/death_row/dr_info/wesbrookcoylast.html"},
{"weight":3,"rank":19.0, "id":67, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garciagustavolast.html"},
{"weight":3,"rank":19.0, "id":68, "url":"https://www.tdcj.texas.gov/death_row/dr_info/freemanjames.html"},
{"weight":3,"rank":19.0, "id":69, "url":"https://www.tdcj.texas.gov/death_row/dr_info/freemanjamesllast.html"},
{"weight":3,"rank":19.0, "id":70, "url":"https://www.tdcj.texas.gov/death_row/dr_info/mastersonrichard.html"},
{"weight":3,"rank":19.0, "id":71, "url":"https://www.tdcj.texas.gov/death_row/dr_info/mastersonrichardlast.html"},
{"weight":3,"rank":19.0, "id":72, "url":"https://www.tdcj.texas.gov/death_row/dr_info/holidayraphael.html"},
{"weight":3,"rank":19.0, "id":73, "url":"https://www.tdcj.texas.gov/death_row/dr_info/holidayraphaellast.html"},
{"weight":3,"rank":19.0, "id":74, "url":"https://www.tdcj.texas.gov/death_row/dr_info/escamillalicho.html"},
{"weight":3,"rank":19.0, "id":75, "url":"https://www.tdcj.texas.gov/death_row/dr_info/escamillalicholast.html"},
{"weight":3,"rank":19.0, "id":76, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garciajuan.html"},
{"weight":3,"rank":19.0, "id":77, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garciajuanlast.html"},
{"weight":3,"rank":19.0, "id":78, "url":"https://www.tdcj.texas.gov/death_row/dr_info/lopezdaniel.html"},
{"weight":3,"rank":19.0, "id":79, "url":"https://www.tdcj.texas.gov/death_row/dr_info/lopezdaniellast.html"},
{"weight":3,"rank":19.0, "id":80, "url":"https://www.tdcj.texas.gov/death_row/dr_info/russeaugregory.html"},
{"weight":3,"rank":19.0, "id":81, "url":"https://www.tdcj.texas.gov/death_row/dr_info/russeaugregorylast.html"},
{"weight":3,"rank":19.0, "id":82, "url":"https://www.tdcj.texas.gov/death_row/dr_info/bowerlesterlast.html"},
{"weight":3,"rank":19.0, "id":83, "url":"https://www.tdcj.texas.gov/death_row/dr_info/charlesderrick.html"},
{"weight":3,"rank":19.0, "id":84, "url":"https://www.tdcj.texas.gov/death_row/dr_info/charlesderricklast.html"},
{"weight":3,"rank":19.0, "id":85, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garzamanuel.html"},
{"weight":3,"rank":19.0, "id":86, "url":"https://www.tdcj.texas.gov/death_row/dr_info/garzamanuellast.html"},
{"weight":3,"rank":19.0, "id":87, "url":"https://www.tdcj.texas.gov/death_row/dr_info/sprousekent.html"},
{"weight":3,"rank":19.0, "id":88, "url":"https://www.tdcj.texas.gov/death_row/dr_info/sprousekentlast.html"},
{"weight":3,"rank":19.0, "id":89, "url":"https://www.tdcj.texas.gov/death_row/dr_info/vasquezmanuel.html"},
{"weight":3,"rank":19.0, "id":90, "url":"https://www.tdcj.texas.gov/death_row/dr_info/vasquezmanuellast.html"},
{"weight":3,"rank":19.0, "id":91, "url":"https://www.tdcj.texas.gov/death_row/dr_info/newburydonald.html"},
{"weight":3,"rank":19.0, "id":92, "url":"https://www.tdcj.texas.gov/death_row/dr_info/newburydonaldlast.html"},
{"weight":3,"rank":19.0, "id":93, "url":"https://www.tdcj.texas.gov/death_row/dr_info/laddrobert.html"},
{"weight":3,"rank":19.0, "id":94, "url":"https://www.tdcj.texas.gov/death_row/dr_info/laddrobertlast.html"},
{"weight":3,"rank":19.0, "id":95, "url":"https://www.tdcj.texas.gov/death_row/dr_info/prietoarnoldlast.html"},
{"weight":3,"rank":19.0, "id":96, "url":"https://www.tdcj.texas.gov/death_row/dr_info/paredesmiguel.html"},
{"weight":3,"rank":19.0, "id":97, "url":"https://www.tdcj.texas.gov/death_row/dr_info/paredesmiguellast.html"},
{"weight":3,"rank":19.0, "id":98, "url":"https://www.tdcj.texas.gov/death_row/dr_info/colemanlisa.html"},
{"weight":3,"rank":19.0, "id":99, "url":"https://www.tdcj.texas.gov/death_row/dr_info/colemanlisalast.html"},
{"weight":3,"rank":19.0, "id":100, "url":"https://www.tdcj.texas.gov/death_row/dr_info/trottiewillielast.html"},
{"weight":3,"rank":19.0, "id":101, "url":"https://www.tdcj.texas.gov/death_row/dr_info/villegasjose.html"}],
"links":[
{"source":0,"target":0,"value":3},
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":0,"target":3,"value":3},
{"source":0,"target":4,"value":3},
{"source":0,"target":5,"value":3},
{"source":0,"target":6,"value":3},
{"source":0,"target":7,"value":3},
{"source":0,"target":8,"value":3},
{"source":0,"target":9,"value":3},
{"source":0,"target":10,"value":3},
{"source":0,"target":11,"value":3},
{"source":0,"target":12,"value":3},
{"source":0,"target":13,"value":3},
{"source":0,"target":14,"value":3},
{"source":0,"target":15,"value":3},
{"source":0,"target":16,"value":3},
{"source":0,"target":17,"value":3},
{"source":0,"target":18,"value":3},
{"source":0,"target":19,"value":3},
{"source":0,"target":20,"value":3},
{"source":0,"target":21,"value":3},
{"source":0,"target":22,"value":3},
{"source":0,"target":23,"value":3},
{"source":0,"target":24,"value":3},
{"source":0,"target":25,"value":3},
{"source":0,"target":26,"value":3},
{"source":0,"target":27,"value":3},
{"source":0,"target":28,"value":3},
{"source":0,"target":29,"value":3},
{"source":0,"target":30,"value":3},
{"source":0,"target":31,"value":3},
{"source":0,"target":32,"value":3},
{"source":0,"target":33,"value":3},
{"source":0,"target":34,"value":3},
{"source":0,"target":35,"value":3},
{"source":0,"target":36,"value":3},
{"source":0,"target":37,"value":3},
{"source":0,"target":38,"value":3},
{"source":0,"target":39,"value":3},
{"source":0,"target":40,"value":3},
{"source":0,"target":41,"value":3},
{"source":0,"target":42,"value":3},
{"source":0,"target":43,"value":3},
{"source":0,"target":44,"value":3},
{"source":0,"target":45,"value":3},
{"source":0,"target":46,"value":3},
{"source":0,"target":47,"value":3},
{"source":0,"target":48,"value":3},
{"source":0,"target":49,"value":3},
{"source":0,"target":50,"value":3},
{"source":0,"target":51,"value":3},
{"source":0,"target":52,"value":3},
{"source":0,"target":53,"value":3},
{"source":0,"target":54,"value":3},
{"source":0,"target":55,"value":3},
{"source":0,"target":56,"value":3},
{"source":0,"target":57,"value":3},
{"source":0,"target":58,"value":3},
{"source":0,"target":59,"value":3},
{"source":0,"target":60,"value":3},
{"source":0,"target":61,"value":3},
{"source":0,"target":62,"value":3},
{"source":0,"target":63,"value":3},
{"source":0,"target":64,"value":3},
{"source":0,"target":65,"value":3},
{"source":0,"target":66,"value":3},
{"source":0,"target":67,"value":3},
{"source":0,"target":68,"value":3},
{"source":0,"target":69,"value":3},
{"source":0,"target":70,"value":3},
{"source":0,"target":71,"value":3},
{"source":0,"target":72,"value":3},
{"source":0,"target":73,"value":3},
{"source":0,"target":74,"value":3},
{"source":0,"target":75,"value":3},
{"source":0,"target":76,"value":3},
{"source":0,"target":77,"value":3},
{"source":0,"target":78,"value":3},
{"source":0,"target":79,"value":3},
{"source":0,"target":80,"value":3},
{"source":0,"target":81,"value":3},
{"source":0,"target":82,"value":3},
{"source":0,"target":83,"value":3},
{"source":0,"target":84,"value":3},
{"source":0,"target":85,"value":3},
{"source":0,"target":86,"value":3},
{"source":0,"target":87,"value":3},
{"source":0,"target":88,"value":3},
{"source":0,"target":89,"value":3},
{"source":0,"target":90,"value":3},
{"source":0,"target":91,"value":3},
{"source":0,"target":92,"value":3},
{"source":0,"target":93,"value":3},
{"source":0,"target":94,"value":3},
{"source":0,"target":95,"value":3},
{"source":0,"target":96,"value":3},
{"source":0,"target":97,"value":3},
{"source":0,"target":98,"value":3},
{"source":0,"target":99,"value":3},
{"source":0,"target":100,"value":3},
{"source":37,"target":37,"value":3},
{"source":76,"target":76,"value":3},
{"source":55,"target":55,"value":3},
{"source":66,"target":66,"value":3},
{"source":71,"target":71,"value":3},
{"source":16,"target":16,"value":3},
{"source":40,"target":40,"value":3},
{"source":42,"target":42,"value":3},
{"source":62,"target":62,"value":3},
{"source":72,"target":72,"value":3},
{"source":59,"target":59,"value":3},
{"source":53,"target":53,"value":3},
{"source":92,"target":92,"value":3},
{"source":28,"target":28,"value":3},
{"source":10,"target":10,"value":3},
{"source":15,"target":15,"value":3},
{"source":51,"target":51,"value":3},
{"source":12,"target":12,"value":3},
{"source":35,"target":35,"value":3},
{"source":3,"target":3,"value":3},
{"source":61,"target":61,"value":3},
{"source":57,"target":57,"value":3},
{"source":8,"target":8,"value":3},
{"source":94,"target":94,"value":3},
{"source":56,"target":56,"value":3},
{"source":7,"target":7,"value":3},
{"source":95,"target":95,"value":3},
{"source":9,"target":9,"value":3},
{"source":52,"target":52,"value":3},
{"source":77,"target":77,"value":3},
{"source":67,"target":67,"value":3},
{"source":99,"target":99,"value":3},
{"source":65,"target":65,"value":3},
{"source":22,"target":22,"value":3},
{"source":33,"target":33,"value":3},
{"source":48,"target":48,"value":3},
{"source":87,"target":87,"value":3},
{"source":34,"target":34,"value":3},
{"source":31,"target":31,"value":3},
{"source":17,"target":17,"value":3},
{"source":93,"target":93,"value":3},
{"source":85,"target":85,"value":3},
{"source":39,"target":39,"value":3},
{"source":43,"target":43,"value":3},
{"source":38,"target":38,"value":3},
{"source":98,"target":98,"value":3},
{"source":86,"target":86,"value":3},
{"source":64,"target":64,"value":3},
{"source":24,"target":24,"value":3},
{"source":70,"target":70,"value":3},
{"source":45,"target":45,"value":3},
{"source":25,"target":25,"value":3},
{"source":1,"target":1,"value":3},
{"source":18,"target":18,"value":3},
{"source":89,"target":89,"value":3},
{"source":26,"target":26,"value":3},
{"source":47,"target":47,"value":3},
{"source":13,"target":13,"value":3},
{"source":63,"target":63,"value":3},
{"source":54,"target":54,"value":3},
{"source":11,"target":11,"value":3},
{"source":96,"target":96,"value":3},
{"source":81,"target":81,"value":3},
{"source":23,"target":23,"value":3},
{"source":82,"target":82,"value":3},
{"source":14,"target":14,"value":3},
{"source":27,"target":27,"value":3},
{"source":21,"target":21,"value":3},
{"source":50,"target":50,"value":3},
{"source":4,"target":4,"value":3},
{"source":100,"target":100,"value":3},
{"source":83,"target":83,"value":3},
{"source":2,"target":2,"value":3},
{"source":88,"target":88,"value":3},
{"source":91,"target":91,"value":3},
{"source":29,"target":29,"value":3},
{"source":58,"target":58,"value":3},
{"source":79,"target":79,"value":3},
{"source":78,"target":78,"value":3},
{"source":36,"target":36,"value":3},
{"source":97,"target":97,"value":3},
{"source":49,"target":49,"value":3},
{"source":20,"target":20,"value":3},
{"source":80,"target":80,"value":3},
{"source":69,"target":69,"value":3},
{"source":90,"target":90,"value":3},
{"source":41,"target":41,"value":3},
{"source":74,"target":74,"value":3},
{"source":19,"target":19,"value":3},
{"source":6,"target":6,"value":3},
{"source":32,"target":32,"value":3},
{"source":73,"target":73,"value":3},
{"source":68,"target":68,"value":3},
{"source":30,"target":30,"value":3},
{"source":46,"target":46,"value":3},
{"source":75,"target":75,"value":3},
{"source":84,"target":84,"value":3},
{"source":44,"target":44,"value":3},
{"source":60,"target":60,"value":3},
{"source":5,"target":5,"value":3}]};